spring:
  application:
    name: ${APP_NAME:ServerManagementSystem}

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5430/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}

  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:validate}
    show-sql: ${JPA_SHOW_SQL:true}
    open-in-view: ${JPA_OPEN_IN_VIEW:false}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:true}

  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    locations: ${FLYWAY_LOCATIONS:classpath:db/migration}
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:true}
